---
- name: Install IaaS
  hosts: localhost
  become: yes
  vars:
    ansible_become_password: "{{ iaas_password }}"
  tasks:
    - name: Install
      apt: name={{ item }} state=present update_cache=yes
      with_items:
      - libvirt-daemon-system
      - libvirt-clients
      - python3-libvirt
      - nfs-kernel-server
    - name: Create IaaS folders
      file:
        path: "/export/iaas/{{ item }}"
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777
      with_items:
      - images
      - vms
    - name: Publish IaaS folders
      lineinfile:
        path: /etc/exports
        state: present
        line: "/export/iaas *(rw,sync,all_squash,no_subtree_check,insecure)"
    - name: Restart NFS
      systemd:
        daemon_reload: yes
        state: started
        name: nfs-kernel-server.service
    - name: Export share
      command: exportfs -a

